### ISSUE TITLE
Add pytest 7 compatibility

### ISSUE THREAD

**Issue by dmkoch** [ClearcodeHQ/pytest-elasticsearch#376]
### What action do you want to perform

Trying to use `pytest-elasticsearch==2.1.0` with `pytest==7.0.0`

### What are the results

`pytest` run crashes with:

```
  File "/usr/local/lib/python3.9/site-packages/pytest_elasticsearch/factories.py", line 26, in <module>
    from _pytest.tmpdir import TempdirFactory
ImportError: cannot import name 'TempdirFactory' from '_pytest.tmpdir' (/usr/local/lib/python3.9/site-packages/_pytest/tmpdir.py)
```

### What are the expected results

pytest-elasticsearch works with pytest 7.0+

**Comment by fizyk** [comment]
@dmkoch the tmpdir_factory fixture with tmp_path_factory fixture.

The minimum supported pytest version should then be set to 6.2 
ref: https://github.com/ClearcodeHQ/pytest-postgresql/issues/533

**Comment by fizyk** [comment]
added
